### ISSUE TITLE
Navbar collapse scroll not working

### ISSUE THREAD

**Issue by Bagmaz** [creativetimofficial/now-ui-kit-pro#10]
Hi,
Navbar collapse scroll not working

<img width="400" alt="screen shot 2018-03-12 at 1 04 15 pm" src="https://user-images.githubusercontent.com/20259560/37282785-fd6364a8-25f5-11e8-9a8d-d4199fb98d7c.png">
  
I use `overflow-y: scroll;` but then I have another problem with the background color

<img width="400" alt="screen shot 2018-03-12 at 1 08 50 pm" src="https://user-images.githubusercontent.com/20259560/37282963-887fa416-25f6-11e8-8b5d-d72b992b1248.png">

**Comment by dragosct10** [comment]
Hi, @Bagmaz! To fix this please add on the `ul` tag with the class `.navbar-nav`, not the div with class `.navbar-collapse` the following properties: 

```css
    position: relative;
    max-height: calc(100vh - 75px);
    min-height: 100%;
    overflow: auto;
```

Regards,
Dragos

**Comment by Bagmaz** [comment]
Hi, @dragosct10 Please fix this on next version.

**Comment by Bagmaz** [comment]
Now I have a another problem.

When I use 
```
position: relative;
    max-height: calc(100vh - 75px);
    min-height: 100%;
    overflow: auto;
```

<img width="400" alt="screen shot 2018-03-14 at 11 41 56 am" src="https://user-images.githubusercontent.com/20259560/37397833-e44ae31e-277c-11e8-9971-c25bb28448b9.png">

Then Drop down is gone.

<img width="100" alt="screen shot 2018-03-14 at 11 44 37 am" src="https://user-images.githubusercontent.com/20259560/37397942-3a80f9b2-277d-11e8-8533-8dc508cb0c76.png">

<img width="100" alt="screen shot 2018-03-14 at 11 44 42 am" src="https://user-images.githubusercontent.com/20259560/37397954-415b3680-277d-11e8-898e-7dcead209dbc.png">

**Comment by dragosct10** [comment]
Hi, @Bagmaz! Put that css style on media @media only screen and (max-width: 991px){  }. Regard, Dragos

**Comment by Bagmaz** [comment]
Hi, @dragosct10,
It works.

<img width="375" alt="screen shot 2018-03-14 at 11 52 00 am" src="https://user-images.githubusercontent.com/20259560/37398269-3f5f0824-277e-11e8-9adb-49b7942dd36c.png">

Thank you.
