### ISSUE TITLE
Vue version of ui lacks css for element-ui components such as table spinner

### ISSUE THREAD

**Issue by natesnapp** [creativetimofficial/now-ui-kit-pro#18]
It appears that the loading svg animation for el-table element is sized inappropriately large and is not doing animation. I have a simple test which I have attached and made as a routable content page. This is using the same code from this [this fiddle](https://jsfiddle.net/kghLhege/4/) which has a css applied (unpkg.com/element-ui@2.3.4/lib/theme-chalk/index.css).

See example:
[TestTableSpinner.txt](https://github.com/creativetimofficial/now-ui-kit-pro/files/1911836/TestTableSpinner.txt)

And here is what appears when rendered (image shows an additional disabled button and spinner from previous version of the code.. TestTableSpinner.txt only has bare minimum needed)::
<img width="560" alt="screen shot 2018-04-14 at 5 35 03 pm" src="https://user-images.githubusercontent.com/2713065/38776030-ffcd36e2-4044-11e8-85fd-4b3d3d9f6935.png">

**Comment by dragosct10** [comment]
Hi! Please if you have an issue use the correct GitHub repo. 
https://github.com/creativetimofficial/vue-now-ui-dashboard-pro

Regards,
Dragos

**Comment by natesnapp** [comment]
Thanks for pointing me to the right location. I have created [](https://github.com/creativetimofficial/vue-now-ui-dashboard-pro/issues/9)
