### ISSUE TITLE
 Conflict between bootstrap4 and now-ui-kit-pro

### ISSUE THREAD

**Issue by likexoo** [creativetimofficial/now-ui-kit-pro#19]
I added the css file to the project according to the API：

> ‘To get going, just include assets/css/now-ui-kit.css in your HTML template. ’

and bootstrap styles is a mess

Project info:

- bootstrap 4
- blaze-html-templates 1.1.2
- kadira:blaze-layout 2.3.0

**Comment by likexoo** [comment]
![wechatimg596](https://user-images.githubusercontent.com/15852426/38817686-314fab5a-4199-11e8-88af-ceaf1a2d5f2c.jpeg)

**Comment by dragosct10** [comment]
Hi, @likexoo! Thank you for using our product. Please, tell us which errors did you have? Regards, Dragos

**Comment by likexoo** [comment]
@dragosct10 Hello there!
For example, now-ui will cover the style ".nav" of bootstrap

- without now-ui:
![wechatimg600](https://user-images.githubusercontent.com/15852426/38856705-7727d420-4227-11e8-8100-cc729a95a995.jpeg)

- with now-ui:
![wechatimg601](https://user-images.githubusercontent.com/15852426/38856717-815f55f8-4227-11e8-93bb-5cdee7252cf4.jpeg)

my need is to use two styles at the same time

**Comment by bulunluo** [comment]
The same problem,
I want to know if is possible to use the two together without conflict

**Comment by dragosct10** [comment]
Hi! We are built this product on the top of the Bootstrap, so it's normal to cover the style of Bootstrap. To use both navs together it's very hard to achieve this, you can only use one style ( bootstrap or now-ui ). Regards, Dragos
