### ISSUE TITLE
Missing "separator" class

### ISSUE THREAD

**Issue by finkbg** [creativetimofficial/now-ui-kit-pro#2]
This is present in the free version, but missing here. Pro was supposed to add, not remove, right?

**Comment by dragosct10** [comment]
Hi, @finkbg! In the example page from the [link](http://demos.creative-tim.com/now-ui-kit-pro/examples/about-us.html) you will find the separator class. The separator class it's not missing.

Regards,
Dragos

**Comment by finkbg** [comment]
Gotcha, it just changed. Thanks.
