### ISSUE TITLE
Page header image issue

### ISSUE THREAD

**Issue by Bagmaz** [creativetimofficial/now-ui-kit-pro#4]
Hi,

This is for Now Ui Kit PRO

<img width="1295" alt="screen shot 2017-12-22 at 10 25 25 pm" src="https://user-images.githubusercontent.com/20259560/34313510-f5365196-e76b-11e7-8499-fd1a80831175.png">

<img width="1295" alt="screen shot 2017-12-22 at 10 25 31 pm" src="https://user-images.githubusercontent.com/20259560/34313514-fc74657e-e76b-11e7-949b-6f8b6fdcad64.png">

Please fix this like this " Paper Kit 2 "

<img width="1295" alt="screen shot 2017-12-22 at 10 25 51 pm" src="https://user-images.githubusercontent.com/20259560/34313531-167bccfa-e76c-11e7-8a34-1c9628e936a6.png">

**Comment by dragosct10** [comment]
Hi, @Bagmaz! Thank you for using our product. If you want to fix this bug please replace the name of the class from the div with class `.content-center` with `.content`, so in the final your code must look like below example: 

<img width="404" alt="screen shot 2017-12-28 at 12 23 52" src="https://user-images.githubusercontent.com/17456857/34408003-015dfc78-ebca-11e7-9be8-989964d6fe88.png">

Now you have to take the uploaded partial scss and go to `assets/sass/now-ui-kit/_sections.scss` and replace with the uploaded file. After that please compile your scss with [Koala](koala-app.com) and please be sure that your output path is `assets/css/now-ui-kit.css`.
[_sections.scss.zip](https://github.com/creativetimofficial/now-ui-kit-pro/files/1591028/_sections.scss.zip)

Regards,
Dragos

**Comment by NormanEdance** [comment]
Still miss spacings...
![content](https://user-images.githubusercontent.com/10945534/34935389-f04e6156-fa07-11e7-9ce9-42ad1eeedf32.PNG)

**Comment by dragosct10** [comment]
Hi! I will upload again the `_sections.scss` partial which is modified and please take the file and go to `assets/sass/now-ui-kit/_sections.scss` and replace with the new one. After that compile with [Koala](koala-app.com) and please be sure that your output path is `assets/css/now-ui-kit.css`. 
[_sections.scss.zip](https://github.com/creativetimofficial/now-ui-kit-pro/files/1631869/_sections.scss.zip)

Let us know if everything is working fine now! 

Regards,
Dragos
