### ISSUE TITLE
Upgrade to Bootstrap 4 beta 3

### ISSUE THREAD

**Issue by Smilefounder** [creativetimofficial/now-ui-kit-pro#6]
Hello team, as the bootstrap 4 beta 3 has been released. Please help upgrade your beautiful theme.
Thanks a lot.

**Comment by peiche** [comment]
You're a bit late. Version 4 final [has been released](https://blog.getbootstrap.com/2018/01/18/bootstrap-4/).

**Comment by dragosct10** [comment]
Hi! The upgrade of the product on the latest bootstrap version will be available soon. I can't tell you exactly the date but will be in February. 

Regards,
Dragos
